services:
  order:
    container_name: order
    ports:
      - "8084:8081"
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    environment:
      ORDER_DATABASE_HOST: order-db
      ORDER_DATABASE_NAME: order_db
      ORDER_DATABASE_USER: order
      ORDER_DATABASE_PASSWORD: 12345Q
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - common-net

  order-workflow-worker:
    container_name: order-workflow-worker
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - workflow-worker
    environment:
      ORDER_DATABASE_HOST: order-db
      ORDER_DATABASE_NAME: order_db
      ORDER_DATABASE_USER: order
      ORDER_DATABASE_PASSWORD: 12345Q

      ORDER_TEMPORAL_HOST: temporal:7233
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - common-net

  order-message-handler:
    container_name: order-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      ORDER_DATABASE_HOST: order-db
      ORDER_DATABASE_NAME: order_db
      ORDER_DATABASE_USER: order
      ORDER_DATABASE_PASSWORD: 12345Q

      ORDER_AMQP_HOST: rmq
      ORDER_AMQP_USER: guest
      ORDER_AMQP_PASSWORD: guest

      ORDER_TEMPORAL_HOST: temporal:7233
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - common-net

  order-db:
    image: "mysql:8.3"
    container_name: order-db
    command: [ "--max_connections=100" ]
    volumes:
      - "order-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: order_db
      MYSQL_USER: order
      MYSQL_PASSWORD: 12345Q
    ports:
      - "3309:3306"
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s
    networks:
      - common-net

volumes:
  order-db-data:

networks:
  common-net:
    external: true