apiVersion: v1
kind: Secret
metadata:
  name: mysql-notification-service
  namespace: infrastructure
type: Opaque
stringData:
  DB_NAME: "notification_db"
  DB_USER: "notification"
  DB_PASSWORD: "12345Q"