apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-service
  namespace: infrastructure
type: Opaque
stringData:
  # Названия файлов здесь важны, они используются скриптом инициализации
  DB_NAME: user_db
  DB_USER: user
  DB_PASSWORD: 12345Q