syntax = "proto3";
package OrderService;

option go_package = "/.;orderinternalapi";

service OrderInternalAPI {
  // Создание заказа. Возвращает ID созданного заказа.
  rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);

  // Получение заказа по ID.
  rpc FindOrder(FindOrderRequest) returns (FindOrderResponse);
}

// --- Requests / Responses ---

message CreateOrderRequest {
  string customerID = 1;
  repeated CreateOrderItem items = 2;
}

message CreateOrderItem {
  string productID = 1;
  int32 count = 2;
}

message CreateOrderResponse {
  string orderID = 1;
}

message FindOrderRequest {
  string orderID = 1;
}

message FindOrderResponse {
  string orderID = 1;
  string customerID = 2;
  OrderStatus status = 3;
  repeated OrderItem items = 4; // Полная структура для ответа
  string createdAt = 5;
  string updatedAt = 6;
  optional string deletedAt = 7;
}

// Полная структура айтема (для чтения)
message OrderItem {
  string orderID = 1;
  string productID = 2;
  int32 count = 3;
  double totalPrice = 4;
}

enum OrderStatus {
  Open = 0;
  Pending = 1;
  Paid = 2;
  Cancelled = 3;
}